# Generated by Django 4.2.24 on 2025-09-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('servapp', models.TextField(default='')),
                ('catagory', models.CharField(choices=[('TF', 'Throttle Fix'), ('CM', 'Carborator Modify'), ('CC', 'Clutch-Change'), ('TC', 'Tire Change'), ('TS', 'Toweing Service'), ('FE', 'Fuel Emergency')], max_length=2)),
                ('service_image', models.ImageField(upload_to='services')),
            ],
        ),
    ]
